"""RED-PROOF FOR THE DRIFT ESTIMAND — written before the module touched real data.

⛔⛔ THE FAILURE THIS EXISTS TO PREVENT: a sign error. The estimand is

        delta = W2(LIVE) - W2(YOKED)

and coupling means the two speakers are CLOSER when the partner can respond, so
coupling is delta < 0. A flipped subtraction would report the wanted result —
"coupling detected" — from data showing the exact opposite, and nothing in the
output would look wrong. So the sign is asserted in BOTH directions against
synthetic clouds whose answer is known by construction.

⛔ THE SECOND FAILURE: measuring the recording. Each yoked arm contains 40 turns
generated by the live speaker and 40 replayed from a transcript. Pooling them
would put the partner's LIVE behaviour into the null, dragging YOKED toward LIVE
and shrinking the very difference being measured — toward zero, which reads as
"no coupling", so it would not even look like a bug.
"""
import pathlib
import sys

import numpy as np
import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "tools"))

from act2_drift import (CONVERGENCE, DIVERGENCE, cluster_bootstrap,  # noqa: E402
                        own_surfaces, pair_delta, verdict_of)

SCALE = np.array([0.25])


def _cloud(centre, spread, n=7, seed=0):
    rng = np.random.default_rng(seed)
    return (centre + spread * rng.standard_normal(n)).reshape(-1, 1)


# ── ⛔⛔ THE SIGN, IN BOTH DIRECTIONS ────────────────────────────────────────
def test_speakers_CLOSER_when_live_is_NEGATIVE_and_reads_as_convergence():
    """The wanted result must only be produced by data that actually shows it."""
    live_a, live_b = _cloud(0.40, 0.02, seed=1), _cloud(0.44, 0.02, seed=2)
    yok_a, yok_b = _cloud(0.30, 0.02, seed=3), _cloud(0.60, 0.02, seed=4)
    d = pair_delta(live_a, live_b, yok_a, yok_b, SCALE)
    assert d["w2_live"] < d["w2_yoked"]
    assert d["delta"] < 0
    assert verdict_of(d["delta"]) == CONVERGENCE


def test_speakers_FARTHER_when_live_is_POSITIVE_and_reads_as_divergence():
    live_a, live_b = _cloud(0.30, 0.02, seed=1), _cloud(0.60, 0.02, seed=2)
    yok_a, yok_b = _cloud(0.40, 0.02, seed=3), _cloud(0.44, 0.02, seed=4)
    d = pair_delta(live_a, live_b, yok_a, yok_b, SCALE)
    assert d["delta"] > 0
    assert verdict_of(d["delta"]) == DIVERGENCE


def test_identical_conditions_give_exactly_zero():
    a, b = _cloud(0.4, 0.02, seed=1), _cloud(0.5, 0.02, seed=2)
    d = pair_delta(a, b, a, b, SCALE)
    assert d["delta"] == pytest.approx(0.0, abs=1e-12)


def test_the_estimand_is_not_symmetric_under_swapping_the_arms():
    """⛔ Guard on the guard: if swapping LIVE and YOKED did not flip the sign,
    the subtraction is not doing what the name says."""
    la, lb = _cloud(0.40, 0.02, seed=1), _cloud(0.44, 0.02, seed=2)
    ya, yb = _cloud(0.30, 0.02, seed=3), _cloud(0.60, 0.02, seed=4)
    fwd = pair_delta(la, lb, ya, yb, SCALE)["delta"]
    rev = pair_delta(ya, yb, la, lb, SCALE)["delta"]
    assert fwd == pytest.approx(-rev)


# ── the frozen ruler must actually be consumed ──────────────────────────────
def test_the_axis_scale_is_used_not_ignored():
    """⛔ A scale argument that changes nothing is a scale that was recomputed
    internally — the ruler would move with the measurement."""
    la, lb = _cloud(0.40, 0.02, seed=1), _cloud(0.44, 0.02, seed=2)
    ya, yb = _cloud(0.30, 0.02, seed=3), _cloud(0.60, 0.02, seed=4)
    a = pair_delta(la, lb, ya, yb, np.array([0.25]))["delta"]
    b = pair_delta(la, lb, ya, yb, np.array([0.50]))["delta"]
    assert a != pytest.approx(b)


# ── ⛔⛔ NEVER MEASURE THE RECORDING ─────────────────────────────────────────
def _log(*rows):
    return [{"speaker": s, "valid": v, "injected": i, "surface": t}
            for s, v, i, t in rows]


def test_the_replayed_partner_is_excluded_from_a_yoked_arm():
    lg = _log(("A", True, False, "mine-1"), ("B_rec", True, False, "REPLAY-1"),
              ("A", True, False, "mine-2"), ("B_rec", True, False, "REPLAY-2"))
    assert own_surfaces(lg, "A") == ["mine-1", "mine-2"]


def test_a_recording_label_is_never_mistaken_for_its_speaker():
    """`A_rec` must not match a request for `A`."""
    lg = _log(("B", True, False, "mine"), ("A_rec", True, False, "REPLAY"))
    assert own_surfaces(lg, "A") == []
    assert own_surfaces(lg, "B") == ["mine"]


def test_injected_and_invalid_turns_are_dropped():
    lg = _log(("A", True, False, "keep"), ("A", True, True, "injected"),
              ("A", False, False, None), ("A", True, False, "keep2"))
    assert own_surfaces(lg, "A") == ["keep", "keep2"]


# ── the pipeline must not manufacture drift out of nothing ─────────────────
def test_clouds_drawn_from_ONE_distribution_give_a_ci_covering_zero():
    """⛔⛔ THE SELF-PAIR PRECONDITION, in miniature. If identical processes
    produce a confident non-zero delta, the machinery invents the result."""
    rng = np.random.default_rng(11)
    deltas, adapters = [], []
    for k in range(12):
        c = [rng.normal(0.45, 0.05, 7).reshape(-1, 1) for _ in range(4)]
        deltas.append(pair_delta(c[0], c[1], c[2], c[3], SCALE)["delta"])
        adapters.append(("a%d" % (k % 7), "a%d" % ((k + 3) % 7)))
    lo, hi = cluster_bootstrap(deltas, adapters, n_boot=400, seed=5)["ci"]
    assert lo < 0 < hi, "a null dataset produced a confident non-zero drift"


def test_the_bootstrap_CAN_exclude_zero_so_it_has_not_merely_been_consulted():
    """A test that cannot return a negative has not been passed."""
    deltas = [-0.40 - 0.01 * i for i in range(12)]
    adapters = [("a%d" % (i % 7), "a%d" % ((i + 3) % 7)) for i in range(12)]
    lo, hi = cluster_bootstrap(deltas, adapters, n_boot=400, seed=5)["ci"]
    assert hi < 0, "a strong uniform effect was not detected"
