"""THE PROBE BATTERY — PREREG `20620b7c` §3. Built and frozen BEFORE any run.

⛔⛔ THE BATTERY IS THE ANCHOR THE WHOLE OBSERVABLE IS MEASURED AGAINST. If it
can move, drift can be manufactured by moving it. So it is generated by a seeded,
recorded procedure, then FROZEN AND HASHED, and the hash goes in the run ledger
before epoch 0.

Two halves, 32 each (§3.2, §3.3):

  PRODUCTION    "how does this model say X?"  A fixed English stimulus; the
                model renders it; we compare impressions across epochs.
                ⭐ The stimulus is the LITERARY RENDER of a held-out Scene --
                real prose, derived deterministically from the Scene, inventing
                no English of its own. So the probe has a known target and the
                battery is reproducible from the lexicon.

  COMPREHENSION "what does this model take Y to mean?"  A validated Tlon
                surface plus FOUR forced-choice austere glosses: one true and
                three pi-DISTINCT NEAR MISSES.
                ⭐⭐ THE DISTRACTORS ARE THE B2 HARDENING PASS'S OWN MUTATION SET
                -- single denoting-part changes (root / orient / aspect-root /
                edge-relator), already proven pi-distinct and already proven to
                be the near misses a threshold would merge. So comprehension is
                a discrimination test in the SAME COORDINATE as everything else,
                and it needs NO JUDGE MODEL -- which is the point, because a
                judge is a second confabulation engine.
"""
from __future__ import annotations

import hashlib
import json
import random
from dataclasses import dataclass, field

from ..grammar import classes as C
from ..grammar.gloss import gloss
from ..grammar.parse import Scene, render
from ..product import schema as PS
# ⛔ ONE definition of "impression", shared with the product. Re-spelling
# `utterance_id(project(s))` here would be a second fold of the same rule and
# the two could disagree. (Axis 4 forks the LEXICON, not this.)
from ..product.compat import impression

N_PRODUCTION = 32
N_COMPREHENSION = 32
N_CHOICES = 4                      # 1 true + 3 pi-distinct near misses

# Which denoting parts a distractor may be built from. Derived intent, not a
# guess: these are exactly the parts pi keeps and a signature can constrain.
_DISTRACTOR_PARTS = ("root", "orient", "aspect_root", "relator")


class BatteryError(RuntimeError):
    """The battery could not be built to specification. Never a silent shortfall."""


@dataclass(frozen=True)
class ProductionProbe:
    pid: str
    stimulus: str                  # the English the model is asked to render
    target_impression: str         # the impression the stimulus was built from

    @property
    def kind(self) -> str:
        return "production"


@dataclass(frozen=True)
class ComprehensionProbe:
    pid: str
    surface: str                   # a validated Tlon utterance
    options: tuple[str, ...]       # austere glosses; index 0 is NOT the answer
    answer: int                    # index of the true gloss
    target_impression: str
    option_impressions: tuple[str, ...] = field(default=())

    @property
    def kind(self) -> str:
        return "comprehension"


@dataclass(frozen=True)
class Battery:
    production: tuple[ProductionProbe, ...]
    comprehension: tuple[ComprehensionProbe, ...]
    seed: int
    lexicon: str
    digest: str

    def __len__(self) -> int:
        return len(self.production) + len(self.comprehension)

    def impressions(self) -> frozenset[str]:
        """Every impression the battery touches -- the leakage watch-list."""
        out = {p.target_impression for p in self.production}
        for c in self.comprehension:
            out.add(c.target_impression)
            out.update(c.option_impressions)
        return frozenset(out)


# ── scene generation ──────────────────────────────────────────────────────
def _random_node(rng: random.Random, lex, k, depth: int = 1) -> dict:
    node: dict = {"root": rng.choice(sorted(lex["R"]))}
    if rng.random() < 0.6:
        node["orient"] = rng.sample(sorted(lex["O"]),
                                    rng.randint(1, k["MAX_ORIENT_PER_PRED"]))
    if rng.random() < 0.5:
        node["aspect_root"] = rng.choice(sorted(lex["A"]))
        node["aspect_reps"] = rng.randint(1, k["MAX_ASPECT_REPS"])
    for cls, field_name in (("D", "degree"), ("M", "modal"), ("T", "tense"),
                            ("Q", "quant")):
        if rng.random() < 0.3:
            node[field_name] = rng.choice(sorted(lex[cls]))
    if depth < 2 and rng.random() < 0.7:
        node["edges"] = [{"relator": rng.choice(sorted(lex["L"])),
                          "node": _random_node(rng, lex, k, depth + 1)}]
    return node


def _mutate(node: dict, part: str, rng: random.Random, lex) -> dict | None:
    """A single-denoting-part near miss, or None if this node has no such part."""
    out = json.loads(json.dumps(node))
    if part == "root":
        others = [r for r in sorted(lex["R"]) if r != out["root"]]
        out["root"] = rng.choice(others)
        return out
    if part == "orient":
        cur = out.get("orient") or []
        pool = [o for o in sorted(lex["O"]) if o not in cur]
        if not cur:
            out["orient"] = [rng.choice(pool)]
        else:
            out["orient"] = sorted(cur[:-1] + [rng.choice(pool)])
        return out
    if part == "aspect_root":
        cur = out.get("aspect_root")
        pool = [a for a in sorted(lex["A"]) if a != cur]
        out["aspect_root"] = rng.choice(pool)
        out.setdefault("aspect_reps", 1)
        return out
    if part == "relator":
        if not out.get("edges"):
            return None
        cur = out["edges"][0]["relator"]
        pool = [r for r in sorted(lex["L"]) if r != cur]
        out["edges"][0]["relator"] = rng.choice(pool)
        return out
    raise BatteryError(f"unknown distractor part {part!r}")


def assert_distinct(m_imp: str, answer: str, others: list[str], part: str) -> None:
    """⛔⛔ A TRIPWIRE, NOT A FILTER, AND THE DIFFERENCE IS THE WHOLE POINT.

    The first version silently `continue`d past a distractor that collided with
    the answer. Measured: **14,799 single-part mutations, ZERO collisions** --
    because the B2 hardening pass proved that mutating any denoting part ALONE
    always separates the impression, and these four parts are all denoting. So
    that branch was unreachable, and a test asserting distinctness over a
    generated battery could never come back positive: it was checking a property
    guaranteed upstream, not guarding anything.

    ⭐ SO THE SILENT SKIP BECOMES A LOUD RAISE. If a single-part mutation ever
    DOES land on the same impression, π or `_mutate` is broken and the right
    behaviour is to stop, not to quietly draw another distractor and hand out a
    battery built on a broken assumption.
    """
    if m_imp == answer:
        raise BatteryError(
            f"a {part!r} mutation left the impression unchanged. Mutating a "
            "denoting part alone must separate the impression (B2); if it does "
            "not, π or the mutation is broken and every near-miss distractor in "
            "this battery is suspect.")
    if m_imp in others:
        raise BatteryError(
            f"a {part!r} mutation collided with another distractor. Two options "
            "sharing an impression make the probe unanswerable, and a model "
            "picking either would score as having changed its mind.")


def _validate(node: dict, force: str) -> tuple[Scene, str] | None:
    try:
        scene, surface, _ = PS.validate(
            {"node": node, "force": force, "refused_objects": [], "note": ""})
    except PS.ProposalError:
        return None
    return scene, surface


def build(seed: int = 20620, *, n_prod: int = N_PRODUCTION,
          n_comp: int = N_COMPREHENSION) -> Battery:
    """Generate, then freeze. ⛔ Raises rather than returning a short battery: a
    battery quietly smaller than specified changes the power of every test
    computed on it."""
    from ..product.literary import literary          # local: avoids a cycle

    rng = random.Random(seed)
    lex, k = C.load()["classes"], C.constraints()
    forces = sorted(lex["F"])

    prod: list[ProductionProbe] = []
    comp: list[ComprehensionProbe] = []
    seen: set[str] = set()
    guard = 0

    while (len(prod) < n_prod or len(comp) < n_comp) and guard < 40000:
        guard += 1
        node = _random_node(rng, lex, k)
        got = _validate(node, rng.choice(forces))
        if got is None:
            continue
        scene, surface = got
        imp = impression(scene)
        if imp in seen:                 # a battery must not probe one impression twice
            continue

        if len(prod) < n_prod:
            seen.add(imp)
            prod.append(ProductionProbe(pid=f"P{len(prod):02d}",
                                        stimulus=literary(scene),
                                        target_impression=imp))
            continue

        # comprehension: needs three pi-distinct near misses that all validate
        options, imps = [gloss(scene)], [imp]
        for part in rng.sample(_DISTRACTOR_PARTS, len(_DISTRACTOR_PARTS)):
            if len(options) == N_CHOICES:
                break
            mutated = _mutate(node, part, rng, lex)
            if mutated is None:
                continue
            got_m = _validate(mutated, scene.force)
            if got_m is None:
                continue
            m_scene, _ = got_m
            m_imp = impression(m_scene)
            assert_distinct(m_imp, imp, imps, part)
            options.append(gloss(m_scene))
            imps.append(m_imp)
        if len(options) != N_CHOICES:
            continue

        seen.add(imp)
        order = list(range(N_CHOICES))
        rng.shuffle(order)
        shuffled = [options[i] for i in order]
        shuffled_imps = [imps[i] for i in order]
        comp.append(ComprehensionProbe(
            pid=f"C{len(comp):02d}", surface=surface,
            options=tuple(shuffled), answer=order.index(0),
            target_impression=imp, option_impressions=tuple(shuffled_imps)))

    if len(prod) != n_prod or len(comp) != n_comp:
        raise BatteryError(
            f"battery short: {len(prod)}/{n_prod} production, "
            f"{len(comp)}/{n_comp} comprehension after {guard} attempts. A "
            "battery smaller than specified silently changes the power of every "
            "test computed on it.")

    blob = json.dumps(
        {"seed": seed,
         "production": [[p.pid, p.stimulus, p.target_impression] for p in prod],
         "comprehension": [[c.pid, c.surface, list(c.options), c.answer,
                            c.target_impression] for c in comp]},
        sort_keys=True, ensure_ascii=False)
    return Battery(production=tuple(prod), comprehension=tuple(comp), seed=seed,
                   lexicon=C.load()["_hash"],
                   digest=hashlib.sha256(blob.encode("utf-8")).hexdigest()[:16])


# ── F5, the leakage falsifier (PREREG §2 F5) ──────────────────────────────
@dataclass(frozen=True)
class LeakageReport:
    leaked: tuple[str, ...]
    checked: int

    @property
    def rate(self) -> float:
        return len(self.leaked) / self.checked if self.checked else 0.0

    @property
    def void(self) -> bool:
        """> 20 % of the battery lost ⇒ the run is void and re-run with a fresh
        battery (PREREG §2 F5). Held-out probes are not achievable otherwise."""
        return self.rate > 0.20


def leakage(battery: Battery, conversation_impressions) -> LeakageReport:
    """Which probes appeared in the conversation before being administered.

    ⛔ Agreement on a leaked probe is RECALL, NOT CONVENTION, and it inflates C
    in exactly the direction the claim wants. Leaked probes are excluded BEFORE
    unblinding, never after looking at the result.
    """
    said = set(conversation_impressions)
    leaked = []
    for p in battery.production:
        if p.target_impression in said:
            leaked.append(p.pid)
    for c in battery.comprehension:
        if c.target_impression in said:
            leaked.append(c.pid)
    return LeakageReport(leaked=tuple(sorted(leaked)), checked=len(battery))
